window.esdocSearchIndex = [
  [
    "cpceed-web-app/cpceed-webapp/src/server/core/connection.js~connection",
    "class/cpceed-webapp/src/server/core/connection.js~Connection.html",
    "<span>Connection</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/core/connection.js</span>",
    "class"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/auth/auth-manager.js~changeemail",
    "function/index.html#static-function-changeEmail",
    "<span>changeEmail</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/auth/auth-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/auth/auth-manager.js~changepassword",
    "function/index.html#static-function-changePassword",
    "<span>changePassword</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/auth/auth-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/connection.js~close",
    "function/index.html#static-function-close",
    "<span>close</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/connection.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/core/utils.js~comparepassword",
    "function/index.html#static-function-comparePassword",
    "<span>comparePassword</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/core/utils.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/users/user-models.js~comparepassword",
    "function/index.html#static-function-comparePassword",
    "<span>comparePassword</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/users/user-models.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/events/event-manager.js~createevent",
    "function/index.html#static-function-createEvent",
    "<span>createEvent</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/events/event-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/events.js~createevent",
    "function/index.html#static-function-createEvent",
    "<span>createEvent</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/events.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/reports/report-manager.js~createreport",
    "function/index.html#static-function-createReport",
    "<span>createReport</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/reports/report-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/reports.js~createreport",
    "function/index.html#static-function-createReport",
    "<span>createReport</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/reports.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/users/user-manager.js~createuser",
    "function/index.html#static-function-createUser",
    "<span>createUser</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/users/user-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/user.js~createuser",
    "function/index.html#static-function-createUser",
    "<span>createUser</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/user.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/events/event-manager.js~deleteevent",
    "function/index.html#static-function-deleteEvent",
    "<span>deleteEvent</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/events/event-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/reports/report-manager.js~deletereport",
    "function/index.html#static-function-deleteReport",
    "<span>deleteReport</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/reports/report-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/core/utils.js~deletesessionsbyemail",
    "function/index.html#static-function-deleteSessionsByEmail",
    "<span>deleteSessionsByEmail</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/core/utils.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/users/user-manager.js~deleteuser",
    "function/index.html#static-function-deleteUser",
    "<span>deleteUser</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/users/user-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/user.js~deleteuser",
    "function/index.html#static-function-deleteUser",
    "<span>deleteUser</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/user.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/core/connection.js~errorhandler",
    "function/index.html#static-function-errorHandler",
    "<span>errorHandler</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/core/connection.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/events.js~getallevents",
    "function/index.html#static-function-getAllEvents",
    "<span>getAllEvents</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/events.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/reports/report-manager.js~getallreports",
    "function/index.html#static-function-getAllReports",
    "<span>getAllReports</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/reports/report-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/reports.js~getallreports",
    "function/index.html#static-function-getAllReports",
    "<span>getAllReports</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/reports.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/core/utils.js~getcollection",
    "function/index.html#static-function-getCollection",
    "<span>getCollection</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/core/utils.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/events.js~getevent",
    "function/index.html#static-function-getEvent",
    "<span>getEvent</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/events.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/events/event-manager.js~geteventbyid",
    "function/index.html#static-function-getEventById",
    "<span>getEventById</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/events/event-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/reports.js~getreport",
    "function/index.html#static-function-getReport",
    "<span>getReport</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/reports.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/reports/report-manager.js~getreportbyid",
    "function/index.html#static-function-getReportById",
    "<span>getReportById</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/reports/report-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/user.js~getuser",
    "function/index.html#static-function-getUser",
    "<span>getUser</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/user.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/users/user-manager.js~getuserbyid",
    "function/index.html#static-function-getUserById",
    "<span>getUserById</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/users/user-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/core/connection.js~instance",
    "variable/index.html#static-variable-instance",
    "<span>instance</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/core/connection.js</span>",
    "variable"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/auth/auth-manager.js~login",
    "function/index.html#static-function-login",
    "<span>login</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/auth/auth-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/user-auth.js~login",
    "function/index.html#static-function-login",
    "<span>login</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/user-auth.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/auth/auth-manager.js~logout",
    "function/index.html#static-function-logout",
    "<span>logout</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/auth/auth-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/user-auth.js~logout",
    "function/index.html#static-function-logout",
    "<span>logout</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/user-auth.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/events/event-manager.js~modifyevent",
    "function/index.html#static-function-modifyEvent",
    "<span>modifyEvent</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/events/event-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/events.js~modifyevent",
    "function/index.html#static-function-modifyEvent",
    "<span>modifyEvent</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/events.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/reports/report-manager.js~modifyreport",
    "function/index.html#static-function-modifyReport",
    "<span>modifyReport</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/reports/report-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/reports.js~modifyreport",
    "function/index.html#static-function-modifyReport",
    "<span>modifyReport</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/reports.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/users/user-manager.js~modifyuser",
    "function/index.html#static-function-modifyUser",
    "<span>modifyUser</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/users/user-manager.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/user.js~modifyuser",
    "function/index.html#static-function-modifyUser",
    "<span>modifyUser</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/user.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/core/utils.js~newifpresent",
    "function/index.html#static-function-newIfPresent",
    "<span>newIfPresent</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/core/utils.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/connection.js~open",
    "function/index.html#static-function-open",
    "<span>open</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/connection.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/events.js~removeevent",
    "function/index.html#static-function-removeEvent",
    "<span>removeEvent</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/events.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/src/server/reports.js~removereport",
    "function/index.html#static-function-removeReport",
    "<span>removeReport</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/src/server/reports.js</span>",
    "function"
  ],
  [
    "cpceed-web-app/cpceed-webapp/api/auth/auth-manager.js~verify",
    "function/index.html#static-function-verify",
    "<span>verify</span> <span class=\"search-result-import-path\">cpceed-web-app/cpceed-webapp/api/auth/auth-manager.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "cpceed-webapp/api/app.js",
    "file/cpceed-webapp/api/app.js.html",
    "cpceed-webapp/api/app.js",
    "file"
  ],
  [
    "cpceed-webapp/api/auth/auth-manager.js",
    "file/cpceed-webapp/api/auth/auth-manager.js.html",
    "cpceed-webapp/api/auth/auth-manager.js",
    "file"
  ],
  [
    "cpceed-webapp/api/auth/auth-router.js",
    "file/cpceed-webapp/api/auth/auth-router.js.html",
    "cpceed-webapp/api/auth/auth-router.js",
    "file"
  ],
  [
    "cpceed-webapp/api/connection.js",
    "file/cpceed-webapp/api/connection.js.html",
    "cpceed-webapp/api/connection.js",
    "file"
  ],
  [
    "cpceed-webapp/api/core/logger.js",
    "file/cpceed-webapp/api/core/logger.js.html",
    "cpceed-webapp/api/core/logger.js",
    "file"
  ],
  [
    "cpceed-webapp/api/core/logger.js~-",
    "typedef/index.html#static-typedef--",
    "cpceed-webapp/api/core/logger.js~-",
    "typedef"
  ],
  [
    "cpceed-webapp/api/core/utils.js",
    "file/cpceed-webapp/api/core/utils.js.html",
    "cpceed-webapp/api/core/utils.js",
    "file"
  ],
  [
    "cpceed-webapp/api/errors/auth-errors.js",
    "file/cpceed-webapp/api/errors/auth-errors.js.html",
    "cpceed-webapp/api/errors/auth-errors.js",
    "file"
  ],
  [
    "cpceed-webapp/api/events/event-manager.js",
    "file/cpceed-webapp/api/events/event-manager.js.html",
    "cpceed-webapp/api/events/event-manager.js",
    "file"
  ],
  [
    "cpceed-webapp/api/events/event-models.js",
    "file/cpceed-webapp/api/events/event-models.js.html",
    "cpceed-webapp/api/events/event-models.js",
    "file"
  ],
  [
    "cpceed-webapp/api/events/event-models.js~eventschema",
    "typedef/index.html#static-typedef-EventSchema",
    "cpceed-webapp/api/events/event-models.js~EventSchema",
    "typedef"
  ],
  [
    "cpceed-webapp/api/events/event-router.js",
    "file/cpceed-webapp/api/events/event-router.js.html",
    "cpceed-webapp/api/events/event-router.js",
    "file"
  ],
  [
    "cpceed-webapp/api/events/event-router.js~route-createevent",
    "typedef/index.html#static-typedef-Route-CreateEvent",
    "cpceed-webapp/api/events/event-router.js~Route-CreateEvent",
    "typedef"
  ],
  [
    "cpceed-webapp/api/events/event-router.js~route-createevent",
    "typedef/index.html#static-typedef-Route-CreateEvent",
    "cpceed-webapp/api/events/event-router.js~Route-CreateEvent",
    "typedef"
  ],
  [
    "cpceed-webapp/api/events/event-router.js~route-deleteevent",
    "typedef/index.html#static-typedef-Route-DeleteEvent",
    "cpceed-webapp/api/events/event-router.js~Route-DeleteEvent",
    "typedef"
  ],
  [
    "cpceed-webapp/api/events/event-router.js~route-getallevents",
    "typedef/index.html#static-typedef-Route-GetAllEvents",
    "cpceed-webapp/api/events/event-router.js~Route-GetAllEvents",
    "typedef"
  ],
  [
    "cpceed-webapp/api/events/event-router.js~route-geteventbyid",
    "typedef/index.html#static-typedef-Route-GetEventById",
    "cpceed-webapp/api/events/event-router.js~Route-GetEventById",
    "typedef"
  ],
  [
    "cpceed-webapp/api/events/event-router.js~route-modifyevent",
    "typedef/index.html#static-typedef-Route-ModifyEvent",
    "cpceed-webapp/api/events/event-router.js~Route-ModifyEvent",
    "typedef"
  ],
  [
    "cpceed-webapp/api/objects/response.js",
    "file/cpceed-webapp/api/objects/response.js.html",
    "cpceed-webapp/api/objects/response.js",
    "file"
  ],
  [
    "cpceed-webapp/api/passport-config.js",
    "file/cpceed-webapp/api/passport-config.js.html",
    "cpceed-webapp/api/passport-config.js",
    "file"
  ],
  [
    "cpceed-webapp/api/reports/report-manager.js",
    "file/cpceed-webapp/api/reports/report-manager.js.html",
    "cpceed-webapp/api/reports/report-manager.js",
    "file"
  ],
  [
    "cpceed-webapp/api/reports/report-models.js",
    "file/cpceed-webapp/api/reports/report-models.js.html",
    "cpceed-webapp/api/reports/report-models.js",
    "file"
  ],
  [
    "cpceed-webapp/api/reports/report-router.js",
    "file/cpceed-webapp/api/reports/report-router.js.html",
    "cpceed-webapp/api/reports/report-router.js",
    "file"
  ],
  [
    "cpceed-webapp/api/reports/report-router.js~route-createreport",
    "typedef/index.html#static-typedef-Route-CreateReport",
    "cpceed-webapp/api/reports/report-router.js~Route-CreateReport",
    "typedef"
  ],
  [
    "cpceed-webapp/api/reports/report-router.js~route-createreport",
    "typedef/index.html#static-typedef-Route-CreateReport",
    "cpceed-webapp/api/reports/report-router.js~Route-CreateReport",
    "typedef"
  ],
  [
    "cpceed-webapp/api/reports/report-router.js~route-deletereport",
    "typedef/index.html#static-typedef-Route-DeleteReport",
    "cpceed-webapp/api/reports/report-router.js~Route-DeleteReport",
    "typedef"
  ],
  [
    "cpceed-webapp/api/reports/report-router.js~route-getreportbyid",
    "typedef/index.html#static-typedef-Route-GetReportById",
    "cpceed-webapp/api/reports/report-router.js~Route-GetReportById",
    "typedef"
  ],
  [
    "cpceed-webapp/api/reports/report-router.js~route-modifyreport",
    "typedef/index.html#static-typedef-Route-ModifyReport",
    "cpceed-webapp/api/reports/report-router.js~Route-ModifyReport",
    "typedef"
  ],
  [
    "cpceed-webapp/api/router.js",
    "file/cpceed-webapp/api/router.js.html",
    "cpceed-webapp/api/router.js",
    "file"
  ],
  [
    "cpceed-webapp/api/users/user-manager.js",
    "file/cpceed-webapp/api/users/user-manager.js.html",
    "cpceed-webapp/api/users/user-manager.js",
    "file"
  ],
  [
    "cpceed-webapp/api/users/user-manager.js~createusercallback",
    "typedef/index.html#static-typedef-CreateUserCallback",
    "cpceed-webapp/api/users/user-manager.js~CreateUserCallback",
    "typedef"
  ],
  [
    "cpceed-webapp/api/users/user-manager.js~deleteusercallback",
    "typedef/index.html#static-typedef-DeleteUserCallback",
    "cpceed-webapp/api/users/user-manager.js~DeleteUserCallback",
    "typedef"
  ],
  [
    "cpceed-webapp/api/users/user-manager.js~getusercallback",
    "typedef/index.html#static-typedef-GetUserCallback",
    "cpceed-webapp/api/users/user-manager.js~GetUserCallback",
    "typedef"
  ],
  [
    "cpceed-webapp/api/users/user-manager.js~modifyusercallback",
    "typedef/index.html#static-typedef-ModifyUserCallback",
    "cpceed-webapp/api/users/user-manager.js~ModifyUserCallback",
    "typedef"
  ],
  [
    "cpceed-webapp/api/users/user-models.js",
    "file/cpceed-webapp/api/users/user-models.js.html",
    "cpceed-webapp/api/users/user-models.js",
    "file"
  ],
  [
    "cpceed-webapp/api/users/user-models.js~userschema",
    "typedef/index.html#static-typedef-UserSchema",
    "cpceed-webapp/api/users/user-models.js~UserSchema",
    "typedef"
  ],
  [
    "cpceed-webapp/api/users/user-router.js",
    "file/cpceed-webapp/api/users/user-router.js.html",
    "cpceed-webapp/api/users/user-router.js",
    "file"
  ],
  [
    "cpceed-webapp/api/users/user-router.js~route-createuser",
    "typedef/index.html#static-typedef-Route-CreateUser",
    "cpceed-webapp/api/users/user-router.js~Route-CreateUser",
    "typedef"
  ],
  [
    "cpceed-webapp/api/users/user-router.js~route-createuser",
    "typedef/index.html#static-typedef-Route-CreateUser",
    "cpceed-webapp/api/users/user-router.js~Route-CreateUser",
    "typedef"
  ],
  [
    "cpceed-webapp/api/users/user-router.js~route-deleteuser",
    "typedef/index.html#static-typedef-Route-DeleteUser",
    "cpceed-webapp/api/users/user-router.js~Route-DeleteUser",
    "typedef"
  ],
  [
    "cpceed-webapp/api/users/user-router.js~route-getuser",
    "typedef/index.html#static-typedef-Route-GetUser",
    "cpceed-webapp/api/users/user-router.js~Route-GetUser",
    "typedef"
  ],
  [
    "cpceed-webapp/api/users/user-router.js~route-modifyuser",
    "typedef/index.html#static-typedef-Route-ModifyUser",
    "cpceed-webapp/api/users/user-router.js~Route-ModifyUser",
    "typedef"
  ],
  [
    "cpceed-webapp/src/app.jsx",
    "file/cpceed-webapp/src/App.jsx.html",
    "cpceed-webapp/src/App.jsx",
    "file"
  ],
  [
    "cpceed-webapp/src/components/auth/auth.jsx",
    "file/cpceed-webapp/src/components/Auth/Auth.jsx.html",
    "cpceed-webapp/src/components/Auth/Auth.jsx",
    "file"
  ],
  [
    "cpceed-webapp/src/components/auth/authcontainer.jsx",
    "file/cpceed-webapp/src/components/Auth/AuthContainer.jsx.html",
    "cpceed-webapp/src/components/Auth/AuthContainer.jsx",
    "file"
  ],
  [
    "cpceed-webapp/src/components/auth/login.jsx",
    "file/cpceed-webapp/src/components/Auth/Login.jsx.html",
    "cpceed-webapp/src/components/Auth/Login.jsx",
    "file"
  ],
  [
    "cpceed-webapp/src/components/auth/register.jsx",
    "file/cpceed-webapp/src/components/Auth/Register.jsx.html",
    "cpceed-webapp/src/components/Auth/Register.jsx",
    "file"
  ],
  [
    "cpceed-webapp/src/components/auth/requireauth.jsx",
    "file/cpceed-webapp/src/components/Auth/RequireAuth.jsx.html",
    "cpceed-webapp/src/components/Auth/RequireAuth.jsx",
    "file"
  ],
  [
    "cpceed-webapp/src/components/auth/verify.js",
    "file/cpceed-webapp/src/components/Auth/verify.js.html",
    "cpceed-webapp/src/components/Auth/verify.js",
    "file"
  ],
  [
    "cpceed-webapp/src/components/navbar/navbar.css",
    "file/cpceed-webapp/src/components/NavBar/NavBar.css.html",
    "cpceed-webapp/src/components/NavBar/NavBar.css",
    "file"
  ],
  [
    "cpceed-webapp/src/components/navbar/navbar.jsx",
    "file/cpceed-webapp/src/components/NavBar/NavBar.jsx.html",
    "cpceed-webapp/src/components/NavBar/NavBar.jsx",
    "file"
  ],
  [
    "cpceed-webapp/src/components/navbar/navbarcontainer.jsx",
    "file/cpceed-webapp/src/components/NavBar/NavBarContainer.jsx.html",
    "cpceed-webapp/src/components/NavBar/NavBarContainer.jsx",
    "file"
  ],
  [
    "cpceed-webapp/src/index.jsx",
    "file/cpceed-webapp/src/index.jsx.html",
    "cpceed-webapp/src/index.jsx",
    "file"
  ],
  [
    "cpceed-webapp/src/redux/actions.js",
    "file/cpceed-webapp/src/redux/actions.js.html",
    "cpceed-webapp/src/redux/actions.js",
    "file"
  ],
  [
    "cpceed-webapp/src/redux/reducers.js",
    "file/cpceed-webapp/src/redux/reducers.js.html",
    "cpceed-webapp/src/redux/reducers.js",
    "file"
  ],
  [
    "cpceed-webapp/src/redux/store.js",
    "file/cpceed-webapp/src/redux/store.js.html",
    "cpceed-webapp/src/redux/store.js",
    "file"
  ],
  [
    "cpceed-webapp/src/routes/activity/components/activity.jsx",
    "file/cpceed-webapp/src/routes/Activity/components/Activity.jsx.html",
    "cpceed-webapp/src/routes/Activity/components/Activity.jsx",
    "file"
  ],
  [
    "cpceed-webapp/src/routes/activity/index.js",
    "file/cpceed-webapp/src/routes/Activity/index.js.html",
    "cpceed-webapp/src/routes/Activity/index.js",
    "file"
  ],
  [
    "cpceed-webapp/src/routes/events/components/events.js",
    "file/cpceed-webapp/src/routes/Events/components/Events.js.html",
    "cpceed-webapp/src/routes/Events/components/Events.js",
    "file"
  ],
  [
    "cpceed-webapp/src/routes/events/index.js",
    "file/cpceed-webapp/src/routes/Events/index.js.html",
    "cpceed-webapp/src/routes/Events/index.js",
    "file"
  ],
  [
    "cpceed-webapp/src/routes/settings/components/settings.jsx",
    "file/cpceed-webapp/src/routes/Settings/components/Settings.jsx.html",
    "cpceed-webapp/src/routes/Settings/components/Settings.jsx",
    "file"
  ],
  [
    "cpceed-webapp/src/routes/settings/index.js",
    "file/cpceed-webapp/src/routes/Settings/index.js.html",
    "cpceed-webapp/src/routes/Settings/index.js",
    "file"
  ],
  [
    "cpceed-webapp/src/routes/settings/routes/account/components/account.jsx",
    "file/cpceed-webapp/src/routes/Settings/routes/Account/components/Account.jsx.html",
    "cpceed-webapp/src/routes/Settings/routes/Account/components/Account.jsx",
    "file"
  ],
  [
    "cpceed-webapp/src/routes/settings/routes/account/components/accountcontainer.jsx",
    "file/cpceed-webapp/src/routes/Settings/routes/Account/components/AccountContainer.jsx.html",
    "cpceed-webapp/src/routes/Settings/routes/Account/components/AccountContainer.jsx",
    "file"
  ],
  [
    "cpceed-webapp/src/routes/settings/routes/account/index.js",
    "file/cpceed-webapp/src/routes/Settings/routes/Account/index.js.html",
    "cpceed-webapp/src/routes/Settings/routes/Account/index.js",
    "file"
  ],
  [
    "cpceed-webapp/src/routes/settings/routes/profile/components/profile.jsx",
    "file/cpceed-webapp/src/routes/Settings/routes/Profile/components/Profile.jsx.html",
    "cpceed-webapp/src/routes/Settings/routes/Profile/components/Profile.jsx",
    "file"
  ],
  [
    "cpceed-webapp/src/routes/settings/routes/profile/components/profilecontainer.jsx",
    "file/cpceed-webapp/src/routes/Settings/routes/Profile/components/ProfileContainer.jsx.html",
    "cpceed-webapp/src/routes/Settings/routes/Profile/components/ProfileContainer.jsx",
    "file"
  ],
  [
    "cpceed-webapp/src/routes/settings/routes/profile/index.js",
    "file/cpceed-webapp/src/routes/Settings/routes/Profile/index.js.html",
    "cpceed-webapp/src/routes/Settings/routes/Profile/index.js",
    "file"
  ],
  [
    "cpceed-webapp/src/server/core/connection.js",
    "file/cpceed-webapp/src/server/core/connection.js.html",
    "cpceed-webapp/src/server/core/connection.js",
    "file"
  ],
  [
    "cpceed-webapp/src/server/core/connection.js~connection#all",
    "class/cpceed-webapp/src/server/core/connection.js~Connection.html#instance-method-all",
    "cpceed-webapp/src/server/core/connection.js~Connection#all",
    "method"
  ],
  [
    "cpceed-webapp/src/server/core/connection.js~connection#data",
    "class/cpceed-webapp/src/server/core/connection.js~Connection.html#instance-method-data",
    "cpceed-webapp/src/server/core/connection.js~Connection#data",
    "method"
  ],
  [
    "cpceed-webapp/src/server/core/connection.js~connection#params",
    "class/cpceed-webapp/src/server/core/connection.js~Connection.html#instance-method-params",
    "cpceed-webapp/src/server/core/connection.js~Connection#params",
    "method"
  ],
  [
    "cpceed-webapp/src/server/core/connection.js~onapicallfinished",
    "typedef/index.html#static-typedef-OnApiCallFinished",
    "cpceed-webapp/src/server/core/connection.js~OnApiCallFinished",
    "typedef"
  ],
  [
    "cpceed-webapp/src/server/events.js",
    "file/cpceed-webapp/src/server/events.js.html",
    "cpceed-webapp/src/server/events.js",
    "file"
  ],
  [
    "cpceed-webapp/src/server/index.js",
    "file/cpceed-webapp/src/server/index.js.html",
    "cpceed-webapp/src/server/index.js",
    "file"
  ],
  [
    "cpceed-webapp/src/server/reports.js",
    "file/cpceed-webapp/src/server/reports.js.html",
    "cpceed-webapp/src/server/reports.js",
    "file"
  ],
  [
    "cpceed-webapp/src/server/user-auth.js",
    "file/cpceed-webapp/src/server/user-auth.js.html",
    "cpceed-webapp/src/server/user-auth.js",
    "file"
  ],
  [
    "cpceed-webapp/src/server/user.js",
    "file/cpceed-webapp/src/server/user.js.html",
    "cpceed-webapp/src/server/user.js",
    "file"
  ],
  [
    "cpceed-webapp/src/server/utils.js",
    "file/cpceed-webapp/src/server/utils.js.html",
    "cpceed-webapp/src/server/utils.js",
    "file"
  ]
]